#ifndef DRIVER_UTILS_H_
#define DRIVER_UTILS_H_
/* driver_utils.h :: the header file for the driver_utils.c
 * file, this file contains function headers and detailed docs
 * on all functions in the driver_utils.c file
 *
 * To Document : 
 *      - is_source_or_path
 *
 */

/* inclusions from c standart */
#include <stdio.h>

/* homemade inclusions */
#include "../util/boolean.h"
#include "flag_table.h"



/* parse_flags : parses the flags from the given command
 *
 * Arguments :
 *      - cmd : type char * : the command that started the driver
 *      - flags : type FlagLookupTable * : the table where we will put the flags
 *
 * Returns :
 *      - 0 if everything went well, if any other number, something went wrong
 *
 * NOTE : function takes a boolean array of size FLAGSNUM, with different numbers associated with different flags
 *
 */
int parse_flags(char *cmd, FlagLookupTable *flags); 


/* TODO document
 *
 */
boolean is_source_or_path(char *string);


/* preprocess :: runs the gcc preprocessor on our input file (the .c file)
 *
 * Arguments :
 *      - input_file : type char * : the .c file we are preprocessing
 *      - flags : type FlagLookupTable : the lookup table of cmd line flags 
 *
 * Returns : 0 if nothing went wrong, otherwise the error code for the gcc command
 *
 */
int preprocess(char *input_file, FlagLookupTable flags);


/* assemblink : runs the gcc assembler and linker on the .s  assembly file
 *  generated by the compiler
 *
 * Arguments :
 *      - input_file : type char * : the .s file we are assembling
 *      - flags : type FlagLookupTable : the  lookup table of cmd line flags
 *
 * Returns : 0 if nothing went wrong, otherwise the error code for the gcc command
 *
 */
int assemblink(char *input_file, FlagLookupTable flags); 


/* get_source : extracts the source file from the command line arguments, and 
 * places it in the given source variable
 *
 * Arguments :
 *      - cmd : type char * : the command that started the driver
 *      - source : type char * : where we will put the extracted source file
 *
 * Returns:
 *      - a nonzero number if something went wrong, otherwise it returns 0 if everything went well
 *
 */
int get_source(char *cmd, char *source);

#endif
